#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.app_name_ui
  labels:
    app: #@ data.values.app_name_ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ data.values.app_name_ui 
  template:
    metadata:
      labels:
        app: #@ data.values.app_name_ui
    spec:
      containers:
        - name: #@ data.values.app_name_ui
          image: #@ data.values.uiimage.url
          env: 
            - name: "VITE_API_BASE_URL"
              value: #@ data.values.backend_url
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.app_name_ui + "-service"
spec:
  type: NodePort
  selector:
    app: #@ data.values.app_name_ui
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "ui.versioning.demo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: #@ data.values.app_name_ui + "-service"
            port:
              number: 8080
