#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.app_name_ui
  labels:
    app: #@ data.values.app_name_ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ data.values.app_name_ui 
  template:
    metadata:
      labels:
        app: #@ data.values.app_name_ui
    spec:
      containers:
        - name: #@ data.values.app_name_ui
          image: #@ data.values.uiimage.url
          ports:
            - containerPort: 5080
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.app_name_ui
spec:
  type: NodePort
  selector:
    app: #@ data.values.app_name_ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5080
      nodePort: 30080 
