#@ load("@ytt:data", "data")
---
apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: #@ data.values.app_name
  labels:
    app: #@ data.values.app_name
spec:
  replicas: 1
  workerOptions:
    connectionRef:
      name: #@ data.values.temporal_namespace.split(".",1)[0]
    temporalNamespace: #@ data.values.temporal_namespace
  rollout:
    strategy: Progressive
    steps: 
      - rampPercentage: 10
        pauseDuration: 30s
      - rampPercentage: 80
        pauseDuration: 30s
  sunset:
    scaledownDelay: 2m
    deleteDelay: 2m
  template:
    metadata:
      labels:
        app: #@ data.values.app_name
    spec:
      containers:
        - name: temporal-worker-versioning-demo
          image: #@ data.values.image.url
          imagePullPolicy: Always
          env:
            - name: ENCRYPT_PAYLOADS
              value: "false"
            - name: TEMPORAL_CERT_PATH
              value: /etc/certs/tls.crt
            - name: TEMPORAL_KEY_PATH
              value: /etc/certs/tls.key
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
          ports:
            - containerPort: 6080
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            secretName: temporal-auth-tls

---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.app_name + "-service"
spec:
  selector:
    app: #@ data.values.app_name
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: "worker.versioning.demo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: #@ data.values.app_name + "-service"
            port:
              number: 80
